[build]
  command = "next build"
  publish = ".next"

[[redirects]]
from = "/winkel/stripwinkel-jopo-de-pojo"
to = "/winkel/stripwinkel-jopo-de-pojo-haarlem"
status = 301
force = false

[[redirects]]
from = "/winkel/stripwinkel-de-strip-aap"
to = "/winkel/stripwinkel-de-strip-aap-enschede"
status = 301
force = false

[[redirects]]
from = "/winkel/stripwinkel-aelix-strips-en-comics"
to = "/winkel/stripwinkel-aelix-strips-en-comics-den-haag"
status = 301
force = false

[[redirects]]
from = "/winkel/stripwinkel-dick-bos"
to = "/winkel/stripwinkel-dick-bos-rotterdam"
status = 301
force = false

[[redirects]]
from = "/winkel/stripwinkel-bul-super"
to = "/winkel/stripwinkel-bul-super-delft"
status = 301
force = false

[[redirects]]
from = "/winkel/the-splendid-utrecht"
to = "/winkel/stripwinkel-the-splendid-utrecht"
status = 301
force = false

[[redirects]]
from = "/plaats/stripwinkels-in-den-haag"
to = "/plaats/den-haag"
status = 301
force = false

[[redirects]]
from = "/winkel/henk-comics-amsterdam"
to = "/winkel/stripwinkel-henk-comics-amsterdam"
status = 301
force = false

[[redirects]]
from = "/sitemap"
to = "/sitemap.xml
status = 301
force = true
